export const DataActionTypes = {
  UPDATE_TPS_DATA: 'UPDATE_TPS_DATA',
  UPDATE_ACT_AGENT: 'UPDATE_ACT_AGENT',
  UPDATE_INACT_AGENT: 'UPDATE_INACT_AGENT',
  UPDATE_CPU_CORE: 'UPDATE_CPU_CORE',
  UPDATE_HOSTS: 'UPDATE_HOSTS',
};
