export const DataActionTypes = {
  UPDATE_TPS_DATA: 'UPDATE_TPS_DATA',
  UPDATE_INFORMATICS_DATA: 'UPDATE_INFORMATICS_DATA',
  UPDATE_ACTIVE_STATUS_DATA: 'UPDATE_ACTIVE_STATUS_DATA',
  UPDATE_SIMULTANEOUS_USER: 'UPDATE_SIMULTANEOUS_USER',
  UPDATE_YESTERDAY_USERS: 'UPDATE_YESTERDAY_USERS',
  UPDATE_TODAY_USERS: 'UPDATE_TODAY_USERS',
};
