export const DataActionTypes = {
  UPDATE_LOADING_STATUS: 'UPDATE_LOADING_STATUS',
  UPDATE_SPOT_DATA: 'UPDATE_SPOT_DATA',
  UPDATE_SERIES_DATA: 'UPDATE_SERIES_DATA',
  UPDATE_QUEUE: 'UPDATE_QUEUE',
  UPDATE_FETCHED_STATUS: 'UPDATE_FETCHED_STATUS',
};
